language: node_js

node_js:
  - 12.13

before_install:
  - nvm install node
  - npm install -g npm@latest

install:
  - yarn

script:
  - yarn build
  - mkdir deploy
  - mkdir deploy/js
  - mv build/* deploy/js
  - mv src/demos/* src/index.html deploy
  - touch deploy/.nojekyll

deploy:
  provider: pages
  local-dir: deploy
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master