language: node_js

node_js:
  - 12.13

before_install:
  - nvm install node
  - npm install -g npm@latest

install:
  - yarn

script:
  - cd visualization
  - yarn build
  - mv build deploy
  - mkdir deploy/demo
  - cp ./demo/*.html deploy/demo
  - mkdir deploy/demo/css
  - cp ./demo/css/*.css deploy/demo/css
  - mkdir deploy/demo/img
  - cp ./demo/img/* deploy/demo/img
  - touch deploy/.nojekyll

deploy:
  provider: pages
  local-dir: deploy
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master